[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimfiler.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'fatih/vim-go'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'vim-erlang/vim-erlang-tags'

[[plugins]]
repo = 'justinmk/vim-dirvish'

[[plugins]]
repo = 'vim-erlang/vim-erlang-omnicomplete'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'airblade/vim-rooter'
