[[plugins]]
'Shougo/dein.vim'

[[plugins]]
'Shougo/vimfiler.vim'

[[plugins]]
'Shougo/vimproc'
build = 'make'

[[plugins]]
'Shougo/deoplete.nvim'

[[plugins]]
'zchee/deoplete-go'
build = 'make'

[[plugins]]
'itchyny/lightline.vim'

[[plugins]]
'Shougo/unite.vim'

[[plugins]]
'ujihisa/unite-colorscheme'

[[plugins]]
'tomasr/molokai'

[[plugins]]
'scrooloose/syntastic'

[[plugins]]
'Shougo/vimshell.vim'

[[plugins]]
'thinca/vim-quickrun'

[[plugins]]
'jiangmiao/auto-pairs'

[[plugins]]
'fatih/vim-go'
